version: "3.8"

services:
  postgres:
    container_name: delicias_vann_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delicias_vann
